#Enabling the repos
- name: RHSM Subscribe | Enabling the satellite repos
  include_role:
    name: oasis_roles.system.rhsm
  vars:
    rhsm_repositories:
      disabled:
        - '*'
      enabled:
        - rhel-7-server-satellite-{{ satellite_version }}-rpms
        - rhel-7-server-rpms
        - rhel-server-rhscl-7-rpms
        - rhel-7-server-satellite-maintenance-6-rpms
        - rhel-7-server-ansible-2.8-rpms
  apply:
    tags:
      - "rhn"
      - "skip_ansible_lint"  # ANSIBLE0012
